# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iXGUsAteJof8BlQOhZvfIJ3ZJo3dOede2lmA757DMRfIgbJiC4GffcHI4qfk/ID41ROB/YnXPqMGAYvK4XgssPjUmsxHCISpqwXT7sYJZjLKVH+yzjAd7BJd7e9HonGiJNpP9902YHMonsppeutCi6Ebxzvfvj4rVSb5rZBQFqC8JoJjwg/QlN72jbx8Z27JcfwH4xvGpxARz06rX2t3vNPQOPzOARhxcRzHhIOg9vLak2bVNsFzqzQelU+okox9NzgUkaVvYAdiszeGaNoO0IUlORHswBd4Kyb8u4v/MCKKLWo06YkxgVAX1kdov+kvJw0xKysmT0uFDzkl9VnhQiiwYZKHB6N+IDFBcr+IGOgBEVdy8cGlT6voFEYUNAcdwmq8NVRboHZ59FD2r0/lLFqW6Ev6Mv4u5VSinaPjjIdhM+Dn3nn0UmWr339kfImB9U1AiUieUToCCeVnT4v8wf5HGKKOUMF0t74dJM7xgT/wKHlGZuSGykAAoqpHuQI5+rkjmOYTsNWZCgSCe6TgSVge6ZuBridCtmrESywUna5C4cdg0dsr/kZQ10bpGX+nh6Y3SmlLZIz4s0TBpULkHTEvlxpGpir0pE1oIiKnsa7f9uS1MASqFI4o4qrk0L4AqwTebLUnOvkIwA4FnYNhdQduZpY193l5GSfIKVOaeYE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
