travis:
  secure:
    BINSTAR_TOKEN: iXGUsAteJof8BlQOhZvfIJ3ZJo3dOede2lmA757DMRfIgbJiC4GffcHI4qfk/ID41ROB/YnXPqMGAYvK4XgssPjUmsxHCISpqwXT7sYJZjLKVH+yzjAd7BJd7e9HonGiJNpP9902YHMonsppeutCi6Ebxzvfvj4rVSb5rZBQFqC8JoJjwg/QlN72jbx8Z27JcfwH4xvGpxARz06rX2t3vNPQOPzOARhxcRzHhIOg9vLak2bVNsFzqzQelU+okox9NzgUkaVvYAdiszeGaNoO0IUlORHswBd4Kyb8u4v/MCKKLWo06YkxgVAX1kdov+kvJw0xKysmT0uFDzkl9VnhQiiwYZKHB6N+IDFBcr+IGOgBEVdy8cGlT6voFEYUNAcdwmq8NVRboHZ59FD2r0/lLFqW6Ev6Mv4u5VSinaPjjIdhM+Dn3nn0UmWr339kfImB9U1AiUieUToCCeVnT4v8wf5HGKKOUMF0t74dJM7xgT/wKHlGZuSGykAAoqpHuQI5+rkjmOYTsNWZCgSCe6TgSVge6ZuBridCtmrESywUna5C4cdg0dsr/kZQ10bpGX+nh6Y3SmlLZIz4s0TBpULkHTEvlxpGpir0pE1oIiKnsa7f9uS1MASqFI4o4qrk0L4AqwTebLUnOvkIwA4FnYNhdQduZpY193l5GSfIKVOaeYE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
