travis:
  secure:
    BINSTAR_TOKEN: jxvce1iCwWuMOg7B/q4+sNaUkZO4zJ3XjYc2sKgNSsIajnlgDVWgB4/TW5A3YCg/SbDC5EsH5YO9zaIFyytJIHN4y/JNSXrdNg7HBjkXR/3rURJgsBlINTAlLOPdIsDbLe0P1Iams+4FqnaB+UIzYKCKjE3QJITXLii3MSUZPUBrzMdqtr8DHTLi5vJ8CqOGaprbgCpb+L1flHU8wwai738s62ERHEAIXNYdPJLdAbUYDMh4+aUkHY741T3fZZZ9Uj0ff78CsDljui0q0ahW3MecbS1zHBg+6cD4YPtdx+jtsIAgU5PpBC5CHv8zPzEKgkezE4lXmwhiq9n+TfwOGbAXGnO+obmf34IlnyRg2AJmiLPgx2//tCeTZD0GHi4TifXJnumeloElgwJaqDT66o7QvWr3bPmt5U4Yj5oKbD57uEQFX4j5aPCB8a2Pa4ssT0/QUmAwWnnV2uhOZcK30nPvqxhQzlZtPj28tXb7kKnEbkj1mgDkDJv6i16Vq54NYazhs3tIRa+20JiuPllKY4sdHW0J1UhwTFijRvSShjebRTNTPP/ka5duiKOmdY9TjGhJQKwcIv+qA1J0pqtYPSF7Cut6WIEX7fDkqEfzmxctbSQEoAQVLNg31hcZYDz5eslGmNaJckfFDqYs4M4RgOEwnBJhqBh58CknxlAXUxU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
